# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Andy' do

  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
